spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb-container:3306/newsmtock
    username: root
    password: system

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE

  servlet:
    multipart:
      max_file_size: 10MB
      max_request_size: 50MB

  messages:
    basename: errors

server:
  servlet:
    session:
      tracking-modes: cookie

file:
  dir: C:\newsmtock\post\post_image\

